### ISSUE TITLE
Browser requires cache clear on any TS file change.

### ISSUE THREAD

**Issue by ghost** [netanelgilad/meteor-angular2-typescript#6]
When I make a save in a TS file, the typical Meteor refresh occurs. However, none of the saved changes in the TS get to the browser unless I manually clear the browser cache. This does not happen to any saves in a .html or .js file in the same project.

**Comment by netanelgilad** [comment]
Hey @revspringjake,
This package is not deprecated, please try using https://github.com/Urigo/Meteor-Angular2.
